# -*- Mode:cmake -*-

# $Id$

find_package(Flagpoll REQUIRED)

flagpoll_check_modules(MODULE_VPR          REQUIRED vpr)
flagpoll_check_modules(MODULE_CPPDOM       REQUIRED cppdom)
flagpoll_check_modules(MODULE_GMTL         REQUIRED gmtl)
flagpoll_check_modules(MODULE_GADGET       REQUIRED gadgeteer)
flagpoll_check_modules(MODULE_VRJuggler    REQUIRED vrjuggler)
flagpoll_check_modules(MODULE_VRJugglerOGL REQUIRED vrjuggler-opengl)

find_libs("${MODULE_VPR_LIBRARIES}"          "${MODULE_VPR_LIBRARY_DIRS}"          VPR_libs)
find_libs("${MODULE_CPPDOM_LIBRARIES}"       "${MODULE_CPPDOM_LIBRARY_DIRS}"       CPPDOM_libs)
find_libs("${MODULE_GADGET_LIBRARIES}"       "${MODULE_GADGET_LIBRARY_DIRS}"       GADGET_libs)
find_libs("${MODULE_VRJuggler_LIBRARIES}"    "${MODULE_VRJuggler_LIBRARY_DIRS}"    VRJUGGLER_libs)
find_libs("${MODULE_VRJugglerOGL_LIBRARIES}" "${MODULE_VRJugglerOGL_LIBRARY_DIRS}" VRJUGGLEROGL_libs)

# cppdom
SET(CPPDOM_INCLUDE_DIRS)
LIST(APPEND CPPDOM_INCLUDE_DIRS ${MODULE_CPPDOM_INCLUDE_DIRS})

SET(CPPDOM_LIBRARIES)
LIST(APPEND CPPDOM_LIBRARIES ${CPPDOM_libs})

# gmtl
SET(GMTL_INCLUDE_DIRS)
LIST(APPEND GMTL_INCLUDE_DIRS ${MODULE_GMTL_INCLUDE_DIRS})

# vrj
SET(VRJ_INCLUDE_DIRS)
LIST(APPEND VRJ_INCLUDE_DIRS ${MODULE_VPR_INCLUDE_DIRS})
LIST(APPEND VRJ_INCLUDE_DIRS ${MODULE_GMTL_INCLUDE_DIRS})
LIST(APPEND VRJ_INCLUDE_DIRS ${MODULE_GADGET_INCLUDE_DIRS})
LIST(APPEND VRJ_INCLUDE_DIRS ${MODULE_VRJuggler_INCLUDE_DIRS})
LIST(APPEND VRJ_INCLUDE_DIRS ${MODULE_VRJugglerOGL_INCLUDE_DIRS})

SET(VRJ_LIBRARIES)
LIST(APPEND VRJ_LIBRARIES ${VRJUGGLEROGL_libs})

# vpr
SET(VPR_INCLUDE_DIRS)
LIST(APPEND VPR_INCLUDE_DIRS ${MODULE_VPR_INCLUDE_DIRS})

SET(VPR_LIBRARIES)
LIST(APPEND VPR_LIBRARIES ${VPR_libs})

# $Id$
