
FIND_PACKAGE(OGRE REQUIRED)

IF(OGRE_FOUND)
    MESSAGE(STATUS "Found OGRE")
    MESSAGE(STATUS " -- headers '${OGRE_INCLUDE_DIRS}'")
    MESSAGE(STATUS " -- libs    '${OGRE_LIBRARIES}'")
ENDIF(OGRE_FOUND)

